### ISSUE TITLE
brings an error when I type in npm run login

### ISSUE THREAD

**Issue by Brakerciti** [knyzorg/pluralsight-scraper#29] opened 2020-04-30 18:15 UTC
npm ERR! missing script: login

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sam\AppData\Roaming\npm-cache\_logs\2020-04-30T18_09_50_653Z-debug.log

What should I do ?

**Comment by evo-home-task** [comment] 2020-04-30 19:27
You should be inside `pluralsight-scraper` directory

**Comment by vezaynk** [comment] 2020-04-30 19:30
Duplicate of #23

**Closed as completed by vezaynk** 2020-04-30 19:30 UTC
